/*
 * Quay Frontend
 *
 * This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations. You can find out more at <a href=\"https://quay.io\">Quay</a>.
 *
 * API version: v1
 * Contact: support@quay.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package quay

// Optional data for creating a robot
type CreateRobot struct {
	// Optional unstructured metadata for the robot
	UnstructuredMetadata *interface{} `json:"unstructured_metadata,omitempty"`
	// Optional text description for the robot
	Description string `json:"description,omitempty"`
}
