/*
 * Quay Frontend
 *
 * This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations. You can find out more at <a href=\"https://quay.io\">Quay</a>.
 *
 * API version: v1
 * Contact: support@quay.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package quay

type UpdateMirrorConfigExternalRegistryConfig struct {
	// Proxy configuration for use during synchronization.
	Proxy *interface{} `json:"proxy,omitempty"`
	// Determines whether HTTPs is required and the certificate is verified when communicating with the external repository.
	VerifyTls bool `json:"verify_tls,omitempty"`
}
