/*
 * Quay Frontend
 *
 * This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations. You can find out more at <a href=\"https://quay.io\">Quay</a>.
 *
 * API version: v1
 * Contact: support@quay.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package quay

// Description of updates for a service key
type PutServiceKey struct {
	// The expiration date as a unix timestamp
	Expiration *interface{} `json:"expiration,omitempty"`
	// The friendly name of a service key
	Name string `json:"name,omitempty"`
	// The key/value pairs of this key's metadata
	Metadata *interface{} `json:"metadata,omitempty"`
}
